CREATE TABLE cases
(
    caseId         BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    creationDate   TIMESTAMP     NOT NULL,
    lastUpdateDate TIMESTAMP     NOT NULL,
    title          VARCHAR(255)  NOT NULL,
    description    VARCHAR(2056) NOT NULL
);